### ISSUE TITLE
NfcCx crash in P2P mode with RF_DISCOVER_NTF

### ISSUE THREAD

**Issue by cricard13** [Microsoft/NFC-Class-Extension-Driver#10]
During the NFC Forum Plugfest 2017 in Fremont we found evidence of a NfcCx crash (NULL pointer access).
This is happening in the following conditions at least one RF_DISCOVER_NTF with at least one "RF Technology and Mode" in Poll coming in position 1 or greater.

I have been able to validate a fix but not able to run the HLK again.
Will share a patch for early review.

**Comment by icherniukh** [comment]
fixed in [59cf58b062e4e06d37d9c1cc49ed8218fdda072a](https://github.com/Microsoft/NFC-Class-Extension-Driver/commit/59cf58b062e4e06d37d9c1cc49ed8218fdda072a)
